### ISSUE TITLE
Error loading wav

### ISSUE THREAD

**Issue by drone1** [paulnasca/paulstretch_python#7]
Hi Paul,

I'm trying to run this on MacOS High Sierra 10.13.6. Python 2.7.10.

I've tried a variety of wav files from sample packs and so forth as a test, and have gotten nothing but "Error loading wav..."; I added a bit of code to get more information. Seems I get a ValueError exception, which contains the following: "string size must be a multiple of element size"

It is triggered from this line:

```
wavedata=scipy.io.wavfile.read(filename)
```

I can dig further but was hoping you might just have an idea of what might be wrong here.

All I did was clone, copy a wav to the working directory as a.wav, then run:

    ./paulstretch_stereo.py a.wav b.wav

Full output:

```
Paul's Extreme Sound Stretch (Paulstretch) - Python version 20141220
by Nasca Octavian PAUL, Targu Mures, Romania

stretch amount = 8
window size = 0.25 seconds
Error loading wav: a.wav
Traceback (most recent call last):
  File "./paulstretch_stereo.py", line 149, in <module>
    (samplerate,smp)=load_wav(args[0])
TypeError: 'NoneType' object is not iterable
```

**Comment by ojczeo** [comment]
Fixed it here:
https://github.com/ojczeo/paulstretch_python

**Comment by canyondust** [comment]
@ojczeo Thank you for updating the script. It seems 24bit causes level problems (clipping) and the script also fails under Python 3.8 (numpy 1.19.4, scipy 1.5.4) with the following error:

"Traceback (most recent call last):
  File "./paulstretch_stereo.py", line 153, in <module>
    paulstretch(samplerate,smp,options.stretch,options.window_size,args[1])
  File "./paulstretch_stereo.py", line 124, in paulstretch
    outfile.writeframes(int16(output.ravel(1)*32767.0).tostring())
TypeError: order must be str, not int"

I'll try to fix it myself, but I know nothing about Python. However if you have time, and the fix is easy, it would be beneficial to macOS uses are Python 2 is depricated as of macOS 10.16+

Thanks!

**Comment by usworked** [comment]
Hi @canyondust 
Hope this helps you buddy.. change the output.writeframes line to this:
`outfile.writeframes(int16(output.ravel('F')*32767.0).tostring())`

**Comment by canyondust** [comment]
Heyya @usworked I this is such a coincidence you write now, because I hadn't done much with the code until YESTERDAY when I rewrote the IO to use the soundfile library instead of the wavefile library and added 24-bit support as well :)

**Comment by Mikec78660** [comment]
Wow funny. I just grabbed this utility for a project I was working on. got the same error. "TypeError: order must be str, not int""  Didn't think there was a chance it was still maintained after 9 years and saw the fix. Works great! Thank you for writing this.

**Comment by TheWilley** [comment]
## The Fix
I managed to fix the problem by replacing this line:
```py
outfile.writeframes(int16(output.ravel(1)*32767.0).tostring())
```

With this:
```py
outfile.writeframes(int16(output.ravel('F')*32767.0).tobytes())
```

## Explanation
Exactly two changes were made:
1. We replace `1` in `output.ravel()` to `F`
2. We replace `tostring()` with `tobytes()`

### 1. Fixing incorrect parameter in the `ravel` function
Per the [NumPy documentation](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html), the `ravel` function return a contiguous flattened array. It takes two parameters: `(a: array_like, order: {C,F,A,K}`) . The second parameter (`order`) is the most important one, as we replace `1` with `F`, which fixes the problem, but why? 

You see, this line of code has been unchanged since the [original 2011 release of paulstretch_python](https://github.com/paulnasca/paulstretch_python/blob/ec0dac976e890c18fb50340de1d1d8fc1f83174e/paulstretch_stereo.py#L118C1-L118C71). In 2011, NumPy *did* in fact accept other values than `C,F,A,K` in the `order` parameter, assuming paul was using the last stable version at the time, which was [`1.6.0`](https://github.com/numpy/numpy/releases/tag/v1.6.0) . However, they later outlined [plans to change this in their 1.11.0 notes](https://github.com/numpy/numpy/blob/8f68377c0e90f8ff9a996e801ad0ba2c5971ec3b/doc/source/release/1.11.0-notes.rst?plain=1#L343-L350). Essentially `1` represented `F` at the time, but this is no longer the case. 

<details>
<summary><b>Extra Reading - What does the "order" parameter do?</b></summary>

The order parameter in `numpy.ravel()` is for controlling how a multi-dimensional array is "flattened" into a one-dimensional array. It dictates the sequence in which the elements are read from the input array. The different options dictate how this is done.

`F` stands for "Fortran-style" and reads elements *column by column*. The example below should hopefully give you an idea of how it work.
```py
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flat_arr_f = np.ravel(arr, order='F')
print(flat_arr_f) # Output: [1 4 2 5 3 6]
```
</details>

### 2. Replacing `tostring` with `tobytes`
In NumPy version 2.3.0 the `tostring` function [was officially removed in favor of `tobytes`](https://numpy.org/doc/stable/release/2.3.0-notes.html). In practice both functions did the same thing - [constructing Python bytes containing the raw data bytes in a array](https://numpy.org/doc/1.13/reference/generated/numpy.ndarray.tostring.html?highlight=tostring#numpy.ndarray.tostring). `tostring` simply served as an alias for `tobytes` for a while before it was officially removed.
